version: "3.9"
services:
  db:
    container_name: db-certamen
    image: mysql:8.0
    ports:
      - "3310:3310"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: certamen_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-certamen
  web:
    container_name: certamen-web
    depends_on:
      - db
    ports:
      - "8085:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-certamen
networks:
  net-certamen:
    
